name: pydata-global-dask
channels:
  - conda-forge
dependencies:
  - python=3.8
  - dask=2.27.0
  - fsspec=0.8.3
  - s3fs=0.5.1
  - python-graphviz
  # JupyterLab extensions
  - nodejs
  - jupyterlab>=2.0.0
  - dask-labextension>=2.0.0
  - ipywidgets